services:
  - type: web
    name: homie-website
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: HOMIE_ADMIN_PASS
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: HOMIE_ZALO
        value: "0902866717"
      - key: HOMIE_HOTLINE
        value: "0902 866 717"
      - key: HOMIE_DIACHI
        value: "TP. Đông Hà, Quảng Trị"
